name = "Report"
version = "0.1.0"
license = "license"
author = "adityan"
maintainer = "official.adityan@gmail.com"
copyright = "Copyright 2022, adityan"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
